bahmutov/find-cypress-specs

- .github/workflows/ci.yml
- README.md
- bin/find.js
- cypress/e2e/featureA/user.js
- cypress/e2e/spec.js
- package-lock.json
- package.json
- closes #2
- parameter is `--names` or `-n`
> feat: print suites and test names in each spec

- src/index.js
> Support TypeScript

- .github/workflows/ci.yml
- README.md
- src/index.js
- test-ts-import/.gitignore
- test-ts-import/cypress.config.ts
- test-ts-import/cypress/e2e/spec1.cy.ts
- test-ts-import/cypress/e2e/spec2.cy.ts
- test-ts-import/package-lock.json
- test-ts-import/package.json
- test-ts-import/tsconfig.json
- test-ts/tsconfig.json
> fix: load TS config with import keyword

- .github/workflows/pr.yml
- README.md
- bin/find.js
- cypress/e2e/spec.cy.js
- package-lock.json
- package.json
> feat: add --set-gha-outputs

- .github/workflows/pr.yml
- .gitignore
- README.md
- bin/find.js
- package-lock.json
- package.json
> feat: add caching and timing tracing dependencies

- README.md
- bin/find.js
> feat: add --max-added-traced-specs parameter

- .github/workflows/ci.yml
- README.md
- bin/find.js
- cypress.config.js
- package.json
- src/index.js
- test-components/comp1.cy.js
- test-components/comp2.cy.ts
- test/npm/get-specs.js
> feat: find component specs

- bin/find.js
> fix: set GHA outputs after filtering by tag

- .github/workflows/badges.yml
- README.md
- bin/find.js
- package-lock.json
- package.json
- src/badge.js
- closes #135 
```
$ npx find-cypress-specs --test-counts --update-badge
4 e2e tests, 2 component tests
⚠️ Could not find test count badge
Insert new badge on the first line
saving updated readme with new test counts
```
> feat: add badge command

- package-lock.json
- package.json
- src/index.js
- test/basic.js
to fix issue with globby expecting an array to ignore
> fix: always pass ignore array

- .github/workflows/ci.yml
- .github/workflows/pr.yml
- README.md
- bin/find.js
> feat: set tagged specs as GHA output

- bin/find.js
- package-lock.json
- package.json
> feat: trace jsx and tsx files

- .github/workflows/merge.yml
- .github/workflows/pr.yml
- README.md
- bin/find.js
> Add summary

- .github/workflows/ci.yml
- .github/workflows/pr.yml
- README.md
- package-lock.json
- package.json
- src/index.js
- test-modules/.gitignore
- test-modules/cypress.config.js
- test-modules/cypress/e2e/spec1.cy.js
- test-modules/package-lock.json
- test-modules/package.json
- test (failing for now) for #228
> add test for module import

- .github/workflows/pr.yml
- README.md
- bin/find.js
> feat: add machines computation

- README.md
- bin/find.js
- src/grep.js
- test/grep.js
> feat: add --grep parameter

- src/index.js
> feat: allow CJS Cypress config file, closes #310

- .github/workflows/ci.yml
- .github/workflows/pr.yml
- bin/find.js
- cypress.config.js
- cypress/html-e2e/test-html.cy.js
- cypress/tsconfig.json
- package-lock.json
- package.json
- src/output-html.js
> feat: output html static report

- bin/find.js
- cypress.config.js
- cypress/html-e2e/test-html.cy.js
- cypress/tsconfig.json
- src/count.js
- src/output-html.js
- src/tagged.js
- test/tagged.js
> feat: add test filtering by test tags

- cypress/html-e2e/test-html.cy.js
- src/output-html.js
> fix: sort tags alphabetically

- src/output-html.js
> feat: add modern styles to the report html

- .github/workflows/badges.yml
- .github/workflows/ci.yml
- .github/workflows/merge.yml
- package-lock.json
- package.json
> fix: bump some dependencies
